# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
  end
  config.vm.box_url = "https://f0fff3908f081cb6461b407be80daf97f07ac418.googledrive.com/host/0BwtuV7VyVTSkUG1PM3pCeDJ4dVE/centos7.box"
  config.vm.box = "centos-7-vagrantbox"

  config.vm.synced_folder "../../", "/usr/local/share/go/src/github.com/square/p2"
  config.vm.provision "shell", path: "../common-provision.sh"
end
