// Code generated by protoc-gen-go.
// source: pkg/grpc/scheduler/protos/scheduler.proto
// DO NOT EDIT!

/*
Package scheduler_protos is a generated protocol buffer package.

It is generated from these files:
	pkg/grpc/scheduler/protos/scheduler.proto

It has these top-level messages:
	AllocateNodesRequest
	AllocateNodesResponse
	DeallocateNodesRequest
	DeallocateNodesResponse
*/
package scheduler_protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllocateNodesRequest struct {
	Manifest       string `protobuf:"bytes,1,opt,name=manifest" json:"manifest,omitempty"`
	NodeSelector   string `protobuf:"bytes,2,opt,name=node_selector,json=nodeSelector" json:"node_selector,omitempty"`
	NodesRequested int64  `protobuf:"varint,3,opt,name=nodes_requested,json=nodesRequested" json:"nodes_requested,omitempty"`
}

func (m *AllocateNodesRequest) Reset()                    { *m = AllocateNodesRequest{} }
func (m *AllocateNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*AllocateNodesRequest) ProtoMessage()               {}
func (*AllocateNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllocateNodesRequest) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *AllocateNodesRequest) GetNodeSelector() string {
	if m != nil {
		return m.NodeSelector
	}
	return ""
}

func (m *AllocateNodesRequest) GetNodesRequested() int64 {
	if m != nil {
		return m.NodesRequested
	}
	return 0
}

type AllocateNodesResponse struct {
	AllocatedNodes []string `protobuf:"bytes,1,rep,name=allocated_nodes,json=allocatedNodes" json:"allocated_nodes,omitempty"`
}

func (m *AllocateNodesResponse) Reset()                    { *m = AllocateNodesResponse{} }
func (m *AllocateNodesResponse) String() string            { return proto.CompactTextString(m) }
func (*AllocateNodesResponse) ProtoMessage()               {}
func (*AllocateNodesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllocateNodesResponse) GetAllocatedNodes() []string {
	if m != nil {
		return m.AllocatedNodes
	}
	return nil
}

type DeallocateNodesRequest struct {
	NodesReleased []string `protobuf:"bytes,1,rep,name=nodes_released,json=nodesReleased" json:"nodes_released,omitempty"`
	NodeSelector  string   `protobuf:"bytes,2,opt,name=node_selector,json=nodeSelector" json:"node_selector,omitempty"`
}

func (m *DeallocateNodesRequest) Reset()                    { *m = DeallocateNodesRequest{} }
func (m *DeallocateNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*DeallocateNodesRequest) ProtoMessage()               {}
func (*DeallocateNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeallocateNodesRequest) GetNodesReleased() []string {
	if m != nil {
		return m.NodesReleased
	}
	return nil
}

func (m *DeallocateNodesRequest) GetNodeSelector() string {
	if m != nil {
		return m.NodeSelector
	}
	return ""
}

type DeallocateNodesResponse struct {
}

func (m *DeallocateNodesResponse) Reset()                    { *m = DeallocateNodesResponse{} }
func (m *DeallocateNodesResponse) String() string            { return proto.CompactTextString(m) }
func (*DeallocateNodesResponse) ProtoMessage()               {}
func (*DeallocateNodesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*AllocateNodesRequest)(nil), "scheduler_protos.AllocateNodesRequest")
	proto.RegisterType((*AllocateNodesResponse)(nil), "scheduler_protos.AllocateNodesResponse")
	proto.RegisterType((*DeallocateNodesRequest)(nil), "scheduler_protos.DeallocateNodesRequest")
	proto.RegisterType((*DeallocateNodesResponse)(nil), "scheduler_protos.DeallocateNodesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for P2Scheduler service

type P2SchedulerClient interface {
	AllocateNodes(ctx context.Context, in *AllocateNodesRequest, opts ...grpc.CallOption) (*AllocateNodesResponse, error)
	DeallocateNodes(ctx context.Context, in *DeallocateNodesRequest, opts ...grpc.CallOption) (*DeallocateNodesResponse, error)
}

type p2SchedulerClient struct {
	cc *grpc.ClientConn
}

func NewP2SchedulerClient(cc *grpc.ClientConn) P2SchedulerClient {
	return &p2SchedulerClient{cc}
}

func (c *p2SchedulerClient) AllocateNodes(ctx context.Context, in *AllocateNodesRequest, opts ...grpc.CallOption) (*AllocateNodesResponse, error) {
	out := new(AllocateNodesResponse)
	err := grpc.Invoke(ctx, "/scheduler_protos.P2Scheduler/AllocateNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2SchedulerClient) DeallocateNodes(ctx context.Context, in *DeallocateNodesRequest, opts ...grpc.CallOption) (*DeallocateNodesResponse, error) {
	out := new(DeallocateNodesResponse)
	err := grpc.Invoke(ctx, "/scheduler_protos.P2Scheduler/DeallocateNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for P2Scheduler service

type P2SchedulerServer interface {
	AllocateNodes(context.Context, *AllocateNodesRequest) (*AllocateNodesResponse, error)
	DeallocateNodes(context.Context, *DeallocateNodesRequest) (*DeallocateNodesResponse, error)
}

func RegisterP2SchedulerServer(s *grpc.Server, srv P2SchedulerServer) {
	s.RegisterService(&_P2Scheduler_serviceDesc, srv)
}

func _P2Scheduler_AllocateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2SchedulerServer).AllocateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler_protos.P2Scheduler/AllocateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2SchedulerServer).AllocateNodes(ctx, req.(*AllocateNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2Scheduler_DeallocateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeallocateNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2SchedulerServer).DeallocateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler_protos.P2Scheduler/DeallocateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2SchedulerServer).DeallocateNodes(ctx, req.(*DeallocateNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _P2Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler_protos.P2Scheduler",
	HandlerType: (*P2SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateNodes",
			Handler:    _P2Scheduler_AllocateNodes_Handler,
		},
		{
			MethodName: "DeallocateNodes",
			Handler:    _P2Scheduler_DeallocateNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/scheduler/protos/scheduler.proto",
}

func init() { proto.RegisterFile("pkg/grpc/scheduler/protos/scheduler.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0xdf, 0x4e, 0xb3, 0x40,
	0x10, 0xc5, 0xbf, 0xfd, 0x48, 0x8c, 0x1d, 0x85, 0x9a, 0x8d, 0x7f, 0x90, 0x2b, 0x82, 0xd1, 0xd2,
	0x1b, 0x48, 0xea, 0x0b, 0x68, 0xe2, 0xb5, 0x31, 0xf4, 0x01, 0x08, 0x65, 0xc7, 0xd6, 0x88, 0x2c,
	0x32, 0xdb, 0x7b, 0xdf, 0xd3, 0x97, 0x31, 0xec, 0x02, 0x2a, 0x25, 0xb1, 0x97, 0xfb, 0xdb, 0x33,
	0x73, 0xce, 0x1c, 0x98, 0x57, 0xaf, 0xeb, 0x78, 0x5d, 0x57, 0x79, 0x4c, 0xf9, 0x06, 0xc5, 0xb6,
	0xc0, 0x3a, 0xae, 0x6a, 0xa9, 0x24, 0x7d, 0x83, 0x48, 0x03, 0x7e, 0xd2, 0x83, 0xd4, 0x28, 0x82,
	0x0f, 0x06, 0xa7, 0xf7, 0x45, 0x21, 0xf3, 0x4c, 0xe1, 0xa3, 0x14, 0x48, 0x09, 0xbe, 0x6f, 0x91,
	0x14, 0xf7, 0xe0, 0xf0, 0x2d, 0x2b, 0x5f, 0x9e, 0x91, 0x94, 0xcb, 0x7c, 0x16, 0x4e, 0x92, 0xfe,
	0xcd, 0xaf, 0xc0, 0x2e, 0xa5, 0xc0, 0x94, 0xb0, 0xc0, 0x5c, 0xc9, 0xda, 0xfd, 0xaf, 0x05, 0xc7,
	0x0d, 0x5c, 0xb6, 0x8c, 0xcf, 0x60, 0xda, 0xbc, 0x29, 0xad, 0xcd, 0x46, 0x14, 0xae, 0xe5, 0xb3,
	0xd0, 0x4a, 0x9c, 0xf2, 0x87, 0x0f, 0x8a, 0xe0, 0x0e, 0xce, 0x06, 0x09, 0xa8, 0x92, 0x25, 0x61,
	0xb3, 0x21, 0x6b, 0x3f, 0x44, 0xaa, 0x87, 0x5c, 0xe6, 0x5b, 0xe1, 0x24, 0x71, 0x7a, 0xac, 0x07,
	0x02, 0x01, 0xe7, 0x0f, 0x98, 0x8d, 0x5d, 0x71, 0x0d, 0x4e, 0x17, 0xa2, 0xc0, 0x8c, 0x50, 0xb4,
	0x1b, 0xec, 0x36, 0x83, 0x81, 0x7b, 0x1d, 0x14, 0x5c, 0xc2, 0xc5, 0x8e, 0x8b, 0x49, 0xba, 0xf8,
	0x64, 0x70, 0xf4, 0xb4, 0x58, 0x76, 0xe5, 0xf2, 0x15, 0xd8, 0xbf, 0x4e, 0xe2, 0x37, 0xd1, 0xb0,
	0xf9, 0x68, 0xac, 0x75, 0x6f, 0xf6, 0xa7, 0xce, 0x38, 0x06, 0xff, 0xf8, 0x06, 0xa6, 0x83, 0x38,
	0x3c, 0xdc, 0x9d, 0x1e, 0xef, 0xc5, 0x9b, 0xef, 0xa1, 0xec, 0x9c, 0x56, 0x07, 0x5a, 0x71, 0xfb,
	0x15, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x98, 0x3e, 0xe4, 0x69, 0x02, 0x00, 0x00,
}
