#!/usr/bin/env ruby

# cannot use optionparser - cgexec's option passing style is incompatible with it
loop do
  if ARGV[0] == '--sticky'
    ARGV.shift
  elsif ARGV[0] == '-g'
    ARGV.shift(2)
  else
    break
  end
end

exec ARGV.join(" ")
