// Code generated by protoc-gen-go.
// source: pkg/grpc/podstore/protos/podstore.proto
// DO NOT EDIT!

/*
Package podstore is a generated protocol buffer package.

It is generated from these files:
	pkg/grpc/podstore/protos/podstore.proto

It has these top-level messages:
	SchedulePodRequest
	SchedulePodResponse
	WatchPodStatusRequest
	PodStatusResponse
	ProcessStatus
	ExitStatus
*/
package podstore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SchedulePodRequest struct {
	Manifest string `protobuf:"bytes,1,opt,name=manifest" json:"manifest,omitempty"`
	NodeName string `protobuf:"bytes,2,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
}

func (m *SchedulePodRequest) Reset()                    { *m = SchedulePodRequest{} }
func (m *SchedulePodRequest) String() string            { return proto.CompactTextString(m) }
func (*SchedulePodRequest) ProtoMessage()               {}
func (*SchedulePodRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SchedulePodResponse struct {
	PodUniqueKey string `protobuf:"bytes,1,opt,name=pod_unique_key,json=podUniqueKey" json:"pod_unique_key,omitempty"`
}

func (m *SchedulePodResponse) Reset()                    { *m = SchedulePodResponse{} }
func (m *SchedulePodResponse) String() string            { return proto.CompactTextString(m) }
func (*SchedulePodResponse) ProtoMessage()               {}
func (*SchedulePodResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type WatchPodStatusRequest struct {
	PodUniqueKey    string `protobuf:"bytes,1,opt,name=pod_unique_key,json=podUniqueKey" json:"pod_unique_key,omitempty"`
	WaitIndex       uint64 `protobuf:"varint,2,opt,name=wait_index,json=waitIndex" json:"wait_index,omitempty"`
	StatusNamespace string `protobuf:"bytes,3,opt,name=status_namespace,json=statusNamespace" json:"status_namespace,omitempty"`
}

func (m *WatchPodStatusRequest) Reset()                    { *m = WatchPodStatusRequest{} }
func (m *WatchPodStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchPodStatusRequest) ProtoMessage()               {}
func (*WatchPodStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PodStatusResponse struct {
	Manifest        string           `protobuf:"bytes,1,opt,name=manifest" json:"manifest,omitempty"`
	PodState        string           `protobuf:"bytes,2,opt,name=pod_state,json=podState" json:"pod_state,omitempty"`
	ProcessStatuses []*ProcessStatus `protobuf:"bytes,3,rep,name=process_statuses,json=processStatuses" json:"process_statuses,omitempty"`
	LastIndex       uint64           `protobuf:"varint,4,opt,name=last_index,json=lastIndex" json:"last_index,omitempty"`
}

func (m *PodStatusResponse) Reset()                    { *m = PodStatusResponse{} }
func (m *PodStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*PodStatusResponse) ProtoMessage()               {}
func (*PodStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PodStatusResponse) GetProcessStatuses() []*ProcessStatus {
	if m != nil {
		return m.ProcessStatuses
	}
	return nil
}

type ProcessStatus struct {
	LaunchableId string      `protobuf:"bytes,1,opt,name=launchable_id,json=launchableId" json:"launchable_id,omitempty"`
	EntryPoint   string      `protobuf:"bytes,2,opt,name=entry_point,json=entryPoint" json:"entry_point,omitempty"`
	LastExit     *ExitStatus `protobuf:"bytes,3,opt,name=last_exit,json=lastExit" json:"last_exit,omitempty"`
}

func (m *ProcessStatus) Reset()                    { *m = ProcessStatus{} }
func (m *ProcessStatus) String() string            { return proto.CompactTextString(m) }
func (*ProcessStatus) ProtoMessage()               {}
func (*ProcessStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProcessStatus) GetLastExit() *ExitStatus {
	if m != nil {
		return m.LastExit
	}
	return nil
}

type ExitStatus struct {
	ExitTime   int64 `protobuf:"varint,1,opt,name=exit_time,json=exitTime" json:"exit_time,omitempty"`
	ExitCode   int64 `protobuf:"varint,2,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	ExitStatus int64 `protobuf:"varint,3,opt,name=exit_status,json=exitStatus" json:"exit_status,omitempty"`
}

func (m *ExitStatus) Reset()                    { *m = ExitStatus{} }
func (m *ExitStatus) String() string            { return proto.CompactTextString(m) }
func (*ExitStatus) ProtoMessage()               {}
func (*ExitStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*SchedulePodRequest)(nil), "podstore.SchedulePodRequest")
	proto.RegisterType((*SchedulePodResponse)(nil), "podstore.SchedulePodResponse")
	proto.RegisterType((*WatchPodStatusRequest)(nil), "podstore.WatchPodStatusRequest")
	proto.RegisterType((*PodStatusResponse)(nil), "podstore.PodStatusResponse")
	proto.RegisterType((*ProcessStatus)(nil), "podstore.ProcessStatus")
	proto.RegisterType((*ExitStatus)(nil), "podstore.ExitStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for P2PodStore service

type P2PodStoreClient interface {
	// Schedules a uuid pod on a host
	SchedulePod(ctx context.Context, in *SchedulePodRequest, opts ...grpc.CallOption) (*SchedulePodResponse, error)
	WatchPodStatus(ctx context.Context, in *WatchPodStatusRequest, opts ...grpc.CallOption) (P2PodStore_WatchPodStatusClient, error)
}

type p2PodStoreClient struct {
	cc *grpc.ClientConn
}

func NewP2PodStoreClient(cc *grpc.ClientConn) P2PodStoreClient {
	return &p2PodStoreClient{cc}
}

func (c *p2PodStoreClient) SchedulePod(ctx context.Context, in *SchedulePodRequest, opts ...grpc.CallOption) (*SchedulePodResponse, error) {
	out := new(SchedulePodResponse)
	err := grpc.Invoke(ctx, "/podstore.P2PodStore/SchedulePod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PodStoreClient) WatchPodStatus(ctx context.Context, in *WatchPodStatusRequest, opts ...grpc.CallOption) (P2PodStore_WatchPodStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_P2PodStore_serviceDesc.Streams[0], c.cc, "/podstore.P2PodStore/WatchPodStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &p2PodStoreWatchPodStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type P2PodStore_WatchPodStatusClient interface {
	Recv() (*PodStatusResponse, error)
	grpc.ClientStream
}

type p2PodStoreWatchPodStatusClient struct {
	grpc.ClientStream
}

func (x *p2PodStoreWatchPodStatusClient) Recv() (*PodStatusResponse, error) {
	m := new(PodStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for P2PodStore service

type P2PodStoreServer interface {
	// Schedules a uuid pod on a host
	SchedulePod(context.Context, *SchedulePodRequest) (*SchedulePodResponse, error)
	WatchPodStatus(*WatchPodStatusRequest, P2PodStore_WatchPodStatusServer) error
}

func RegisterP2PodStoreServer(s *grpc.Server, srv P2PodStoreServer) {
	s.RegisterService(&_P2PodStore_serviceDesc, srv)
}

func _P2PodStore_SchedulePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PodStoreServer).SchedulePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podstore.P2PodStore/SchedulePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PodStoreServer).SchedulePod(ctx, req.(*SchedulePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PodStore_WatchPodStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPodStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PodStoreServer).WatchPodStatus(m, &p2PodStoreWatchPodStatusServer{stream})
}

type P2PodStore_WatchPodStatusServer interface {
	Send(*PodStatusResponse) error
	grpc.ServerStream
}

type p2PodStoreWatchPodStatusServer struct {
	grpc.ServerStream
}

func (x *p2PodStoreWatchPodStatusServer) Send(m *PodStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _P2PodStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "podstore.P2PodStore",
	HandlerType: (*P2PodStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SchedulePod",
			Handler:    _P2PodStore_SchedulePod_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPodStatus",
			Handler:       _P2PodStore_WatchPodStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("pkg/grpc/podstore/protos/podstore.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xed, 0xb2, 0x15, 0x4a, 0x26, 0xf4, 0x03, 0x03, 0x22, 0x4a, 0xa9, 0x5a, 0x2d, 0x48, 0x94,
	0x4b, 0x03, 0xe1, 0xc8, 0x0d, 0xc4, 0xa1, 0x02, 0xaa, 0xd5, 0x16, 0xc4, 0xd1, 0x72, 0xd7, 0x43,
	0x62, 0x35, 0x6b, 0xbb, 0x6b, 0xaf, 0x48, 0x7e, 0x01, 0xfc, 0x1a, 0xf8, 0x8b, 0xc8, 0xf6, 0x7e,
	0x85, 0x0f, 0xd1, 0xe3, 0x7b, 0xb3, 0x7e, 0xf3, 0xe6, 0xcd, 0x2c, 0x3c, 0xd5, 0x57, 0xf3, 0xe9,
	0xbc, 0xd4, 0xf9, 0x54, 0x2b, 0x6e, 0xac, 0x2a, 0x71, 0xaa, 0x4b, 0x65, 0x95, 0x69, 0xf1, 0xa9,
	0xc7, 0x64, 0xd0, 0xe0, 0xe4, 0x03, 0x90, 0x8b, 0x7c, 0x81, 0xbc, 0x5a, 0x62, 0xaa, 0x78, 0x86,
	0xd7, 0x15, 0x1a, 0x4b, 0x26, 0x30, 0x28, 0x98, 0x14, 0x5f, 0xd0, 0xd8, 0x71, 0x74, 0x1c, 0x9d,
	0x0c, 0xb3, 0x16, 0x93, 0x03, 0x18, 0x4a, 0xc5, 0x91, 0x4a, 0x56, 0xe0, 0xf8, 0x56, 0x28, 0x3a,
	0xe2, 0x9c, 0x15, 0x98, 0xbc, 0x82, 0x7b, 0x1b, 0x72, 0x46, 0x2b, 0x69, 0x90, 0x3c, 0x81, 0x5d,
	0xad, 0x38, 0xad, 0xa4, 0xb8, 0xae, 0x90, 0x5e, 0xe1, 0xba, 0x56, 0xbd, 0xa3, 0x15, 0xff, 0xe4,
	0xc9, 0x77, 0xb8, 0x4e, 0xbe, 0x45, 0xf0, 0xe0, 0x33, 0xb3, 0xf9, 0x22, 0x55, 0xfc, 0xc2, 0x32,
	0x5b, 0x99, 0xc6, 0xcf, 0x8d, 0xde, 0x93, 0x43, 0x80, 0xaf, 0x4c, 0x58, 0x2a, 0x24, 0xc7, 0x95,
	0xb7, 0xb6, 0x9d, 0x0d, 0x1d, 0x73, 0xe6, 0x08, 0xf2, 0x0c, 0xf6, 0x8d, 0x57, 0xf5, 0xd6, 0x8d,
	0x66, 0x39, 0x8e, 0x63, 0x2f, 0xb3, 0x17, 0xf8, 0xf3, 0x86, 0x4e, 0x7e, 0x46, 0x70, 0xb7, 0x67,
	0xa2, 0x9e, 0xe2, 0x3f, 0xa9, 0x38, 0x87, 0x4e, 0xa8, 0x4d, 0x45, 0x07, 0x05, 0x24, 0xaf, 0x61,
	0x5f, 0x97, 0x2a, 0x47, 0x63, 0x68, 0xe8, 0x84, 0x66, 0x1c, 0x1f, 0xc7, 0x27, 0xa3, 0xd9, 0xc3,
	0xd3, 0x76, 0x33, 0x69, 0xf8, 0xa2, 0xee, 0xb9, 0xa7, 0xfb, 0x10, 0x8d, 0x1b, 0x6e, 0xc9, 0x4c,
	0x33, 0xdc, 0x76, 0x18, 0xce, 0x31, 0x7e, 0xb8, 0xe4, 0x7b, 0x04, 0x3b, 0x1b, 0x0a, 0xe4, 0x31,
	0xec, 0x2c, 0x59, 0x25, 0xf3, 0x05, 0xbb, 0x5c, 0x22, 0x15, 0xbc, 0x89, 0xac, 0x23, 0xcf, 0x38,
	0x39, 0x82, 0x11, 0x4a, 0x5b, 0xae, 0xa9, 0x56, 0x42, 0xda, 0xda, 0x38, 0x78, 0x2a, 0x75, 0x0c,
	0x79, 0x01, 0xbe, 0x09, 0xc5, 0x95, 0xb0, 0x3e, 0xad, 0xd1, 0xec, 0x7e, 0xe7, 0xf9, 0xed, 0x4a,
	0xd8, 0xda, 0xf0, 0xc0, 0x7d, 0xe6, 0x70, 0x32, 0x07, 0xe8, 0x78, 0x17, 0x8c, 0x7b, 0x4b, 0xad,
	0x28, 0xd0, 0x5b, 0x88, 0xb3, 0x81, 0x23, 0x3e, 0x8a, 0x02, 0xdb, 0x62, 0xae, 0x78, 0x48, 0xad,
	0x2e, 0xbe, 0x51, 0x1c, 0xbd, 0x37, 0x57, 0x0c, 0x91, 0xf9, 0xe6, 0x71, 0x06, 0xd8, 0x4a, 0xcf,
	0x7e, 0x44, 0x00, 0xe9, 0xcc, 0xef, 0x49, 0x95, 0x48, 0xde, 0xc3, 0xa8, 0x77, 0x7b, 0xe4, 0x51,
	0x67, 0xf3, 0xcf, 0x0b, 0x9f, 0x1c, 0xfe, 0xa3, 0x1a, 0x56, 0x9d, 0x6c, 0x91, 0x0c, 0x76, 0x37,
	0x6f, 0x91, 0x1c, 0x75, 0x4f, 0xfe, 0x7a, 0xa5, 0x93, 0x83, 0xde, 0x32, 0x7f, 0x3f, 0x9e, 0x64,
	0xeb, 0x79, 0x74, 0x79, 0xdb, 0xff, 0x7d, 0x2f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x4b,
	0x33, 0x36, 0xa8, 0x03, 0x00, 0x00,
}
